basic:
  file_dir: '/Users/Ethan/Desktop/media' #存放资源的主目录路径
  torrent_dir: '/Users/Ethan/Desktop/media' #存放种子文件的路径
  apikey: ''
  agent: 'qb'  #选择做种下载器，qb或tr，只能选择一个
  sticky: 0  #是否置顶，转载请默认0
  stream: 0  #是否不当，转载请默认0
  featured: 0 #是否精选，转载请默认0
  doubleup: 0 #是否双倍上传，转载请默认0


qbittorrent:
  url: '192.168.5.1' #qb路径
  port: '48081'      #qb端口
  username: 'hudan717' #登陆账号
  password: '453040'   #密码
  save_path: '/downlaod'   #qb保存路径
transmission:
  address: '192.168.5.1' #qb路径
  port: '39091'      #qb端口
  username: 'hudan717' #登陆账号
  password: '453040'   #密码
  save_path: '/downlaod/movie'   #qb保存路径