basic:
  file_dir: '/Users/Ethan/Desktop/media'
  torrent_dir: '/Users/Ethan/Desktop/media'
  apikey: ''
  agent: 'qb'  #选择做种下载器，qb或tr，只能选择一个
  pic_num: 6 #选择发种时的截图数量
  internal: 0 #KIMOJI官组专用，请保持0
  personal: 0 #是否为个人作品，即自己抓流、压制、剪辑的作品, 纯转载请保持0

qbittorrent:
  url: '192.168.5.1' #qb路径
  port: ''      #qb端口
  username: '' #登陆账号
  password: ''   #密码
  save_path: '/download'   #qb保存路径
transmission:
  address: '192.168.5.1' #qb路径
  port: ''      #qb端口
  username: '' #登陆账号
  password: ''   #密码
  save_path: '/download'   #qb保存路径