basic: 
  file_dir: '/media' #存放资源的主目录路径
  torrent_dir: '/torrent' #存放种子文件的路径
  username: 'user' #用户名
  password: 'pass' #登陆密码
  pic_num: 3 #选择发种时的截图数量
  internal: 0 #KIMOJI官组专用，请保持0
  personal: 0 #是否为个人作品，即自己抓流、压制、剪辑的作品，不属于任何工作组
qbitorrent:
  url: '192.168.1.1' #qb路径
  port: '8080'      #qb端口
  username: 'admin' #登陆账号
  password: 'adminadmin'   #密码
  save_path: '/downlaod'   #qb保存路径