#!/bin/bash

# 检查当前文件夹是否已经初始化为 Git 仓库
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    # 拉取更新
    git pull origin main
else
    echo "当前文件夹未绑定 Git 仓库，正在绑定 Ethan930717/KIMOJI_ATM 仓库。"
    # 初始化 Git 仓库并添加远程仓库
    git init
    git remote add origin https://github.com/Ethan930717/KIMOJI_ATM.git
    # 拉取更新
    git pull origin main
fi

# 输出结果
echo "KIMOJI_ATM 已更新。"
